[project]
name = "et-dataset"
version = "0.0.1"
description = 'Data preparation for ET dataset'
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-only"
keywords = []
authors = [
  { name = "Emmanuelle Sarrazin", email = "emmanuelle.sarrazin@cnes.fr" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "affine",
  "cdsapi",
  "cftime",
  "geopandas",
  "icoscp_core",
  "numpy",
  "pandas",
  "pyproj",
  "shapely",
  "psutil",
  "fiona",
  "tqdm",
  "xarray",
  "earthaccess",
  "sensorsio",
  "pyBVNET @ git+https://forge.ird.fr/cesbio/modelisation/pybvnet.git@473e4d7490808011b87d4edac91abd16ff93df99",
  "scikit-image",
  "requests",
  "pyarrow",
  "numcodecs",
  "zarr",
  "awscli",
  "fluxnet-shuttle @ git+https://github.com/fluxnet/shuttle.git"
]

[project.optional-dependencies]
dev = [
  "pytest",
  "pip-review",
  "pre-commit",
  "ruff",
  "mypy",
  "line_profiler >=5.0.0,<6",
  "plotly >=6.5.1,<7"
]
notebook = [
  "matplotlib",
  "jupyterlab",
  "notebook",
  "ipywidgets",
  "contextily>=1.7.0,<2",
  "folium >=0.20.0,<0.21",
  "mapclassify >=2.10.0,<3",
  "seaborn",
]

[project.urls]
Source = "https://src.koda.cnrs.fr/trishna/et-dataset"

[project.scripts]
et-dataset = "etdataset.cli:etdataset"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/etdataset","validation/temperature/src/temperature"]

[tool.pytest.ini_options]
addopts = ["-m", "not skip or not slow"]
markers = [
    "unit: mark a test as a unit test.",
    "functional: mark a test a functional test.",
    "end_to_end: mark a test as an end-to-end test.",
    "notebooks: mark a test that runs notebooks.",
    "slow: mark a test that is slow to run.",
    "docs: mark a test for docs.",
    "skip: mark a test that must be skipped.",
    "require_test_data: mark a test that requires ETDATASET_TEST_DATA_PATH environment variable to be set to the test dataset folder",
]
filterwarnings = [
  "ignore",
  "default:::etdataset",
    "ignore::DeprecationWarning:jupyter_client",
        ]
testpaths=["tests"]

[tool.coverage.run]
source = ["etdataset", "tests"]
branch = true
parallel = true
omit = [
  "src/etdataset/__about__.py",
    "./.pixi/*",
  "./hooks/*",
]

[tool.coverage.paths]
et_dataset = ["src/etdataset"]
tests = ["tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.ruff]
line-length = 88
indent-width = 4

[tool.mypy]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
    "affine",
    "earthaccess.*",
    "geopandas",
    "fiona.*",
    "matplotlib.*",
    "scipy.*",
    "rasterio.*",
    "sensorsio.*",
    "shapely.*",
    "theia_picker.*",
    "icoscp_core.*",
    "cdsapi",
    "pytest",
    "math",
    "numpy",
        ]
ignore_missing_imports = true

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64","win-64","osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
et-dataset = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev","notebook"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
pip = ">=25.0.1,<26"
gdal = ">=3.10.2,<4"
hdf4 = ">=4.2.15,<5"
hdf5 = ">=1.14.4,<2"
netcdf4 = ">=1.7.2,<2"
h5netcdf = ">=1.6.1,<2"
rasterio = ">=1.4,<2"
