[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "et-dataset"
dynamic = ["version"]
description = 'Data preparation for ET dataset'
readme = "README.md"
requires-python = ">=3.10"
license = "LicenseRef-Public-Domain"
keywords = []
authors = [
  { name = "Emmanuelle Sarrazin", email = "emmanuelle.sarrazin@cnes.fr" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "affine",
  "cdsapi",
  "cftime",
  "geopandas",
  "numpy",
  "pandas",
  "pyproj",
  "rasterio",
  "shapely",
  "tqdm",
  "xarray",
  "earthaccess",
  "sensorsio",
  "theia-picker",
  "landsatxplore @ git+https://github.com/esarrazin/landsatxplore.git",
]

[project.optional-dependencies]
dev = [
  "hatch",
  "pytest",
  "pip-review",
]
notebook = [
  "matplotlib",
  "jupyterlab",
  "notebook",
  "ipywidgets",
]

[project.urls]
Source = "https://gitlab.cnes.fr/cesbio/et-dataset"

[project.scripts]
et-dataset = "etdataset.cli:etdataset"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/etdataset"]

[tool.hatch.version]
path = "src/etdataset/__about__.py"

[tool.hatch.envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"

[tool.hatch.envs.default]
dependencies = [
  "coverage[toml]>=6.5",
  "pytest",
]
[tool.hatch.envs.default.scripts]
run = "pytest{env:HATCH_TEST_ARGS:} {args}"
run-cov = "coverage run -m pytest{env:HATCH_TEST_ARGS:} {args}"
cov-combine = "coverage combine"
cov-report = "coverage report"

[tool.pytest.ini_options]
filterwarnings = [
  "ignore",
  "default:::etdataset",
        ]

[[tool.hatch.envs.all.matrix]]
python = ["3.10", "3.11", "3.12"]

[tool.hatch.envs.types]
dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/etdataset tests}"

[tool.coverage.run]
source_pkgs = ["etdataset", "tests"]
branch = true
parallel = true
omit = [
  "src/etdataset/__about__.py",
]

[tool.coverage.paths]
et_dataset = ["src/etdataset", "*/et-dataset/src/etdataset"]
tests = ["tests", "*/et-dataset/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.mypy]
exclude = [
    "plot.py",
        ]
plugins = ["numpy.typing.mypy_plugin"]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
    "affine",
    "earthaccess.*",
    "geopandas",
    "fiona.*",
    "landsatxplore.*",
    "matplotlib.*",
    "scipy.*",
    "rasterio.*",
    "sensorsio.*",
    "shapely.*",
    "theia_picker.*",
    "cdsapi",
    "pytest",
        ]
ignore_missing_imports = true

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64","win-64"]

[tool.pixi.pypi-dependencies]
et-dataset = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
notebook = { features = ["notebook"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
python = "3.12.*"
pip = ">=25.0.1,<26"
gdal = ">=3.10.2,<4"
hdf4 = ">=4.2.15,<5"
hdf5 = ">=1.14.4,<2"
netcdf4 = ">=1.7.2,<2"
h5netcdf = ">=1.6.1,<2"
